---
include:
  - board: eyelash_sofle/nrf52840/right
    shield: nice_view
  - board: eyelash_sofle/nrf52840/left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left
  - board: nice_nano/nrf52840
    shield: settings_reset
